#+FILETAGS: :vimwiki:

* Life
#= Life =

[[Health]]

[[AvoidingMistakesInBigDecisions]]
** Health
#= Health =

[[QualitySleep]]

[[SelfDiscipline]]
*** QualitySleep
#= Quality sleep =

Not getting enough sleep negatively affects energy, positvity, productivity
and memory.
Especially in the long run.
The key to avoid daytime sleepiness is to maintain _sleep hygiene_.

The following steps might help:

**** *Cut back on computer after 8 p.m.*
       - The bright light emitted from screens suppresses melatonin production.
       - Turn electronic devices off at least an hour or two before going to bed.
**** *Hide your alarm clock.*
       - Do not watch the clock to see how long does it take you to fall asleep.
       - Do not check the clock to see how long you have left until you need to get up.
       - Such hypervigilance keeps the brain awake.
**** *Make your room comfortably cool.*
       - 12 to 24 degrees is considered _comfortable_.
**** *Don't drink before sleep.*
       - Alcohol helps you fall asleep but reduces sleep quality.
**** *Get your exercise.*
       - Exercising helps you to spend more time in deep sleep.
**** *Follow the 15 minute rule.*
       - If you can't fall asleep (or can't go back to sleep) after 15 minutes, stop trying.
       - Get out of bed, do someting relaxing that will help to clear your head.
           - Reading, meditating, knitting (...)
           - But do NOT use the computer.
       - Go back to bed once you're sleepy again.
**** *Write down stressors.*
       - Do some mental problem-solving before sleeping.
       - Also, you can do it while commuting or showering in the morning.
       - Having the mere sense that you have established a plan for tackling your todos will help you be calm.
*** SelfDiscipline
**** Health - Self-discipline

The pinnacle of self-discipline is a point where whenever you make a conscious decision, you're guaranteed to follow through on it.
While it can empower you to overcome addictions, lose weight, deal with procrastination, disorder and ignorance, it works best when combined with passion, goal-setting and planning.
Without those, you're in danger of moving around very consequently but without any direction.

***** Building self-discipline

Self-discipline is like a muscle. The more you train it, the stronger you become. The less you train it, the weaker you become.

Building self-discipline is analogous to weight training.
Tackle challenges that you can successfully accomplish but which are *near your limit*.
Don't start with weights that you cannot budge and neither with weights that you can lift all day long.

Train progressively - increase the challenge with each success.
Do not try to change everything overnight - setting yourself up for lifting 300kgs will only get you injured.
The more disciplined you become, the more weight you can carry i.e. the easier life gets.

An important note:
    *Do not compare yourself to other people. You will only find what you expect to find. Simply look at where you are now and aim to get better as you go forward.*

***** Acceptance

The first step on the way to building self-discipline is to acknowledge where you are on the road to it.
A few helpful measurements:
****** Do you shower/bathe every day?
****** Do you get up at the same time every morning? Including weekends?
****** Are you overweight?
****** Do you have any addictions (caffeine, nicotine, sugar, etc.) you’d like to break but haven’t?
****** Is your email inbox empty right now?
****** Is your office neat and well organized?
****** Is your home neat and well organized?
****** How much time do you waste in a typical day? On a weekend?
****** If you make a promise to someone, what’s the percentage chance you’ll keep it?
****** If you make a promise to yourself, what’s the percentage chance you’ll keep it?
****** Could you fast for one day?
****** How well organized is your computer’s hard drive?
****** How often do you exercise?
****** What’s the greatest physical challenge you’ve ever faced, and how long ago was it?
****** How many hours of focused work do you complete in a typical workday?
****** How many items on your to do list are older than 90 days?
****** Do you have clear, written goals? Do you have written plans to achieve them?
****** If you lost your job, how much time would you spend each day looking for a new one, and how long would you maintain that level of effort?
****** How much TV do you currently watch? Could you give up TV for 30 days?
****** How do you look right now? What does your appearance say about your level of discipline (clothes, grooming, etc)?
****** Do you primarily select foods to eat based on health considerations or on taste/satiety?
****** When was the last time you consciously adopted a positive new habit? Discontinued a bad habit?
****** Are you in debt? Do you consider this debt an investment or a mistake?
****** Did you decide in advance to be reading this blog right now, or did it just happen?
****** Can you tell me what you’ll be doing tomorrow? Next weekend?
****** On a scale of 1-10, how would you rate your overall level of self-discipline?
****** What more could you accomplish if you could answer that last question with a 9 or 10?

Apart from acknowledging your strong and weak points, you can be in a state of ignorance (you don't know how disciplined you are) or denial (you underestimate or overestimate your level of discipline, leading to choosing unsuitable tasks).

There are different groups of self-discipline e.g.:
****** disciplined sleep,
****** disciplined diet,
****** disciplined work habits,
****** disciplined communication.

***** Willpower

Willpower is the ability to set a course of action and say "Engage!".

Nice example: 
    Products that are aimed to serve as willpower substitutes offer impossible results in a dramatically short period of time.
    This is a safe bet, because people lacking willpower most likely will not take the time to return those products.

Willpower provides a temporary, strong boost.
It burns out quickly, but directed intelligently can overcome inertia.
It is like the D-Day, a great battle that turned the tide of WWII, even though victory was achieved a year later.
To make that kind of effort every day on the war would have been impossible.

The application of willpower includes the following steps:
****** Choose the objective.
****** Create a plan of attack.
****** Execute the plan.

The important thing is to make hit the problem hard and fast in point 3. 
Problems have to be attacked at their weakest points to be cracked easily - so that a high level of willpower is not required every day.
Willpower is unsustainable and *overusing it causes burnout*.

Use willpower to establish a solid foundation for tackling the problem even in days when you will be lacking.
That means changing the environment around the issue and yourself to make dealing with problems easier and more manageable.
Adhering to the 3 points, after choosing the objective, set up a plan of things that have to be done to create  a setting to ease the burdens of dealing with your tasks.
Then execute this plan hard and fast.
The plan can be probably implemented in a day or less.

Don’t use willpower to attack your biggest problem directly.
Use willpower to attack the environmental and social obstacles that perpetuate the problem.
Establish a beachhead first, and then fortify your position i.e. turn it into a habit.

***** Hard work

Hard work is that which challenges you.

Most people will do what's easiest - superficial opportunities in life will be attacked by hordes of people.
Tougher challenges will usually see much less competition and much more opportunity.

Strong challenge is commonly connected with strong results. Sure you can get lucky every once in a while and find an easy path to success. But will you be able to maintain that success, or is it just a fluke? Will you be able to repeat it? Once other people learn how you did it, will you find yourself overloaded with competition?

When you discipline yourself to do what is hard, you gain access to a realm of results that are denied everyone else. The willingness to do what is difficult is like having a key to a special private treasure room.

Hard work pays off. When someone tells you otherwise, beware the sales pitch for something “fast and easy” that’s about to come next. The greater your capacity for hard work, the more rewards fall within your grasp. The deeper you can dig, the more treasure you can potentially find.

Being happy is hard work - true happinesss comes from self-esteem, not from denial and escapism.

***** Industry

Industry is working hard.
It means putting in the time to do the work, be it hard or easy.

Self-discipline requires a capability to put in the time where it's needed.
A lot of messes are created when we refuse to put in the time to do what needs to be done.

There are many problems in life where the solution is largely a brainless time investment.
Emptying the inbox is not a challenging problem - it just requires time.

Disciplining yourself to be industrious allows you to squeeze more value out of your time.
Time is constant, but productivity is not.

A good idea is to keep an eye on your productivity - measure the current level and then gradually ramp it up.
This will cause some hair-pulling days but it will pay off.

Industry is a low level tool.
It will allow you to complete your work efficiently but it will not tell you what work to do in the first place.
Working hard does not necessarily equal working smart.

**** Persistence
    Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. Persistence and determination alone are omnipotent. The slogan “Press On” has solved and always will solve the problems of the human race.

Persistence is the ability to maintain action regardless of your feelings.
It's following the "quitters never win, winners never quit" phrase.
When working on stuff, you will sometimes be motivated, sometimes not.
But it's continuous action that produces results - and persistence allows you to keep taking action even against your motivation.
The good news is that persistence will ultimately provide its own motivation - all the work will start bringing results, which are highly motivating.

Of course, there are times when giving up is the reasonable choice.
Is the plan still correct?
If not, update it.
Is your goal still correct?
If not, update or abandon it.
Don't cling on to things that no longer inspire you - avoid stubbornness.

If possible - find a missions that drives you for a long time, possibly your whole life (like personal growth) and build everything around it.
A general mission like this will enable you to more easily sift through ideas and potential projects and filter out those that do not align with your most precious mission.

The value of persistence comes from a vision of the future that is so compelling that you would give almost anything to make it real.
Following that, persistence of action comes from persistence of vision.
When you're clear about what you want  so that your vision does not change much, you'll be more consistent and persistent in your actions.
That leads to much better results.

Can you identify a part of your life where you’ve demonstrated a pattern of long-term persistence? If you can identify such an area, it may provide a clue to your mission — something you can work towards where passion and self-discipline function synergistically.
** AvoidingMistakesInBigDecisions
*** Avoiding mistakes in big decisions

_via https://medium.com/@evolvable/how-to-avoid-making-huge-mistakes-with-life-s-big-decisions-2e9a71af00bc_

**** The mistakes

*Property Resolution #1:* We would never purchase a property with shared walls again. If we shared a wall with someone, we wanted the freedom to leave at short notice.

*Property Resolution #2:* We would never purchase a property without first living in the immediate area. There’s too much you don’t know until you’ve been a local.

*Property Resolution #3:* We will tell our kids not to bother buying an apartment. Real estate transaction costs are astronomical, so if you’re planning to have a family, and to one day own a house, it might be better to just save for that house.

*Decision Mistake #1:* We hadn’t considered all our options. Once we started to look away from the beach, we saw one apartment, we liked the look of it, and we got railroaded into buying it by a really good salesman. We didn’t look at any other apartments in that suburb. We didn’t ever see any apartments in the suburb we’d planned to look in. Worst of all, we ended up spending more than we’d originally been thinking and it didn’t occur to us to go back to Cronulla to see what this new limit would afford us in the place we really wanted to live.

*Decision Mistake #2:* We weren’t clear on what features were really important to us. After seeing dozens of run-down places in Cronulla, we were blown away by the modern interior of the place we eventually bought. We realised too late that we’d traded that nice interior for things that we valued a lot more: a nice street, quiet surroundings and being near the beach.

**** A better decision process

*#1 List your features:* We wrote down everything that we thought we would like as a feature in a house and property. We’d both lived in at least 5 places by now, and inspected scores more, so it was a pretty long list. We also wrote down things that we definitely didn’t want, but we wrote these as positive items — things we wanted — e.g. “Not next to a power substation.”

*#2 Sort your features:* We sorted the list of features, so that we had a list of most important features to least important. I actually wrote a small computer program that helped us do this by presenting features two at a time and making us choose which was more important. We asked ourselves: “If there were two identical houses except that one had this feature and the other house had the other feature, which would we choose?” We entered this into the program, and it sorted the list based on our answers.

*#3 Score your options:* For every house we visited, we scored the property for each feature out of 5 stars (no half stars allowed!). We kept the whole thing together in one spreadsheet. This gave us a commanding overview of the decision we were making.
