#+FILETAGS: :vimwiki:

* Interview knowledge
** Interview knowledge

*** Personal stuff

My idealistic goal is to be a full-stack, language-agnostic Web/Systems
developer with the ability to design and implement cutting-edge, performant
applications and distributed systems.
I try not to limit myself topic-wise, due to the fact that I'm still discovering
new paradgims and thus I'm open to the possibility of my perspective being
turned upside down.

*** Play ponderings
I see the relationship of Play to JSP as the one between ASP .NET MVC and
ASP .NET.
The differences between the two camps are in terms of lasagna application
approach going against the Web's grain vs a lightweight framework embracing the
Web standards.

Both JSP and standard ASP .NET are in my mind intended for primarily non-Web
oriented developer and try to fit their ways by trying to hide the intricacies
related to developing Web pages.

Scala functional templates remind me greatly Razor templates from MVC3.

What I would like to know is whether there exists a simple way of organising a
Play project per domain aspect - so that MVC directories are at a lower level
than the domain-related ones.
