http://www.allbusiness.com/active-listening-is-an-essential-sales-tool-4001384-1.html
* Listening
You will not learn anything from listening to yourself talk.
Remember also about the reciprocation rule - when you give them attention and
understanding, they will want to give it back to you.
** Hindrances to fully listening
- Are you doing something else when the other person is talking?
  Are you thinking about the next call, how much money will be made from 
  that or about personal concerns?
- During the conversation, do you wait for a pause so that yoyu can spit 
  something out?
- How difficult is it for you to stay quiet?
- Do you talk without thinking beforehand?
- Do you fake listening just s oyou can get in your comments?
- Do you practice selective listening?
- Do you only hear the things you want to hear?
- Are you aware of the message that the person is sending apart from their
  words (body language, facial expressions, eye contact, vocal intonation)?
- Do you allow background noise or the environment to hinder your ability to
  listen?
- Do you listen through filters? When you listen through a filter, your 
  understanding of what you have heard is based on past experiences and 
  beliefs. Passing judgement on people because of their age, success, looks,
  invalidation because of having been in a similar situation with someone 
  else - these create a wall for empathy.
** Ways of improving active listening skills
- *Encourage silence to prove you're actively listening.* Wait for minimum 
  3-4 seconds before responding. Even count in your head. Pause demonstrates
  your interest in what the other party has to say, making them more 
  comfortable and prompting to talk more. It also gives you an opportunity 
  to more often answer thoughtfully.
- *Never interrupt while the other party is speaking.*
- *Be present.* Focus on what the other person is saying, showing genuine 
   interest in them. Have an open and non-judgmental mindset, otherwise you
   risk losing out on subtle cues.
- *Make the other party feel heard.* Clarify what the client has said 
  during the conversation. Rephrase their comments or questions in your own
  words to ensure that you have processed them. Also, you may want to try
  rephrasing other party's words in agreement with them.
- *Become a solution-oriented listener.* Spend more time listening for a 
  solution than you would on the problem.
- *Listen for what is not said.* Reading between the lines is crucial, 
  because what is implied is often more important than what is being said.
  Ask for clarifications, especially when getting seemingly conflicting 
  messages and explore the meaning behind the words and the message that you
  think the other party is trying to communicate.
- *Listen for information.* As opposed to listening *to* information (which
  is just hearing words), you should look under them to explore implied 
  meanings. This prevents preconceived notions and premature judgements or 
  misinterpretations.
  - Listen for what is missing.
  - Listen for concerns the other party might have or what is important to 
    them.
  - Listen for what they value.
  - Listen for what they want and need in order to fill the gap in between.



